version: 2.1

workflows:
  build-deploy:
    jobs:
     - build

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
     
    steps:
    #install qemu
      - run: |
         sudo apt-get install qemu binfmt-support qemu-user-static 
         docker run --rm --privileged multiarch/qemu-user-static --reset -p yes