version: 2.1
commands:
  setup:
    steps:
      - checkout
      - run:
          name: Setup buildx and qemu
          command: |
            sudo apt-get update
            sudo apt-get install -y qemu-user-static
            sudo apt-get install -y binfmt-support
      - run:
          name: Check versions
          command: |
            qemu-arm-static --version
            update-binfmts --version 
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker buildx create --name arm-builder
            docker buildx use arm-builder
            docker buildx inspect --bootstrap
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - setup
      - run:
          name: Login to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name:
          command: |
            DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --platform linux/arm/v7 --push -t icemanaf/rpi-opencv-python .